### ISSUE TITLE
CI: muFFT can't find libmugrid.so 

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/Adhesion#96]
Run source venv/bin/activate
NetCDF configuration:
CDF5 1
Parallel4: 0
PnetCDF: 0
Traceback (most recent call last):
  File "/home/runner/work/Adhesion/Adhesion/.check_mufft_capabilities.py", line 3, in <module>
    import muFFT
  File "/home/runner/work/Adhesion/Adhesion/venv/lib/python3.10/site-packages/muFFT/__init__.py", line 44, in <module>
    import _muGrid
ImportError: libmuGrid.so: cannot open shared object file: No such file or directory
Error: Process completed with exit code 1.

**Comment by sannant** [comment]
since this problem does not arize in SurfaceTopography, something must be done better there
