### ISSUE TITLE
CI: libmuGrid.so not found

### ISSUE THREAD

**Issue by sannant** [ContactEngineering/Adhesion#98]
Problem arizes when the muSpectre is pip installed with --no-binary option 

```
(venv) runner@fv-az800-41:~/work/Adhesion/Adhesion$ python 
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import muFFT 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/runner/work/Adhesion/Adhesion/venv/lib/python3.8/site-packages/muFFT/__init__.py", line 44, in <module>
    import _muGrid
ImportError: libmuGrid.so: cannot open shared object file: No such file or directory
```

prepending the path with 

```
LD_LIBRARY_PATH=$PWD/venv/lib/python3.8/site-packages/:$PWD/venv/lib/python3.8/site-
packages/.muspectre.mesonpy.libs/ 
```
fixes the problem

It is probably a meson-python bug

**Comment by sannant** [comment]
I used https://github.com/lhotari/action-upterm for debugging inside the CI environment

**Comment by sannant** [comment]
Reason was a bug in new mesn-python version 
fixed with new muSpectre release using old meson-pyton
